package actions

import (
	"github.com/apecnascimento/coke/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Cidade)
// DB Table: Plural (cidades)
// Resource: Plural (Cidades)
// Path: Plural (/cidades)
// View Template Folder: Plural (/templates/cidades/)

// CidadesResource is the resource for the Cidade model
type CidadesResource struct {
	buffalo.Resource
}

// List gets all Cidades. This function is mapped to the path
// GET /cidades
func (v CidadesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	cidades := &models.Cidades{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Cidades from the DB
	if err := q.All(cidades); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, cidades))
}

// Show gets the data for one Cidade. This function is mapped to
// the path GET /cidades/{cidade_id}
func (v CidadesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cidade
	cidade := &models.Cidade{}

	// To find the Cidade the parameter cidade_id is used.
	if err := tx.Find(cidade, c.Param("cidade_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, cidade))
}

// New renders the form for creating a new Cidade.
// This function is mapped to the path GET /cidades/new
func (v CidadesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Cidade{}))
}

// Create adds a Cidade to the DB. This function is mapped to the
// path POST /cidades
func (v CidadesResource) Create(c buffalo.Context) error {
	// Allocate an empty Cidade
	cidade := &models.Cidade{}

	// Bind cidade to the html form elements
	if err := c.Bind(cidade); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(cidade)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, cidade))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Cidade was created successfully")

	// and redirect to the cidades index page
	return c.Render(201, r.Auto(c, cidade))
}

// Edit renders a edit form for a Cidade. This function is
// mapped to the path GET /cidades/{cidade_id}/edit
func (v CidadesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cidade
	cidade := &models.Cidade{}

	if err := tx.Find(cidade, c.Param("cidade_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, cidade))
}

// Update changes a Cidade in the DB. This function is mapped to
// the path PUT /cidades/{cidade_id}
func (v CidadesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cidade
	cidade := &models.Cidade{}

	if err := tx.Find(cidade, c.Param("cidade_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Cidade to the html form elements
	if err := c.Bind(cidade); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(cidade)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, cidade))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Cidade was updated successfully")

	// and redirect to the cidades index page
	return c.Render(200, r.Auto(c, cidade))
}

// Destroy deletes a Cidade from the DB. This function is mapped
// to the path DELETE /cidades/{cidade_id}
func (v CidadesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cidade
	cidade := &models.Cidade{}

	// To find the Cidade the parameter cidade_id is used.
	if err := tx.Find(cidade, c.Param("cidade_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(cidade); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Cidade was destroyed successfully")

	// Redirect to the cidades index page
	return c.Render(200, r.Auto(c, cidade))
}
