package actions

import (
	"github.com/apecnascimento/coke/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pessoa)
// DB Table: Plural (pessoas)
// Resource: Plural (Pessoas)
// Path: Plural (/pessoas)
// View Template Folder: Plural (/templates/pessoas/)

// PessoasResource is the resource for the Pessoa model
type PessoasResource struct {
	buffalo.Resource
}

// List gets all Pessoas. This function is mapped to the path
// GET /pessoas
func (v PessoasResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	pessoas := &models.Pessoas{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Pessoas from the DB
	if err := q.All(pessoas); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, pessoas))
}

// Show gets the data for one Pessoa. This function is mapped to
// the path GET /pessoas/{pessoa_id}
func (v PessoasResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pessoa
	pessoa := &models.Pessoa{}

	// To find the Pessoa the parameter pessoa_id is used.
	if err := tx.Find(pessoa, c.Param("pessoa_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pessoa))
}

// New renders the form for creating a new Pessoa.
// This function is mapped to the path GET /pessoas/new
func (v PessoasResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Pessoa{}))
}

// Create adds a Pessoa to the DB. This function is mapped to the
// path POST /pessoas
func (v PessoasResource) Create(c buffalo.Context) error {
	// Allocate an empty Pessoa
	pessoa := &models.Pessoa{}

	// Bind pessoa to the html form elements
	if err := c.Bind(pessoa); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pessoa)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pessoa))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Pessoa was created successfully")

	// and redirect to the pessoas index page
	return c.Render(201, r.Auto(c, pessoa))
}

// Edit renders a edit form for a Pessoa. This function is
// mapped to the path GET /pessoas/{pessoa_id}/edit
func (v PessoasResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pessoa
	pessoa := &models.Pessoa{}

	if err := tx.Find(pessoa, c.Param("pessoa_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pessoa))
}

// Update changes a Pessoa in the DB. This function is mapped to
// the path PUT /pessoas/{pessoa_id}
func (v PessoasResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pessoa
	pessoa := &models.Pessoa{}

	if err := tx.Find(pessoa, c.Param("pessoa_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Pessoa to the html form elements
	if err := c.Bind(pessoa); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(pessoa)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pessoa))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Pessoa was updated successfully")

	// and redirect to the pessoas index page
	return c.Render(200, r.Auto(c, pessoa))
}

// Destroy deletes a Pessoa from the DB. This function is mapped
// to the path DELETE /pessoas/{pessoa_id}
func (v PessoasResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pessoa
	pessoa := &models.Pessoa{}

	// To find the Pessoa the parameter pessoa_id is used.
	if err := tx.Find(pessoa, c.Param("pessoa_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(pessoa); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Pessoa was destroyed successfully")

	// Redirect to the pessoas index page
	return c.Render(200, r.Auto(c, pessoa))
}
